name: Test App
on:
  pull_request:
    branches:
      - main

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install packages
        run: bun install

      - name: Run tests
        run: bun test

      - name: Build app
        run: bun run build
